spring:
  application:
    name: web_scrapping

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

telegram:
  bot:
    token: ${BOT_TOKEN}
    username: ${BOT_USERNAME}